### ISSUE TITLE
Launch the Node.js app error about libLLVM-10.so.1

### ISSUE THREAD

**Issue by anthhub** [second-state/ssvm-nodejs-starter#15]
Launch the Node.js app and then it crash:

```shell
root@8a292042ecf0:/workspaces/ssvm-nodejs-starter# node node/app.js
internal/modules/cjs/loader.js:1122
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: libLLVM-10.so.1: cannot open shared object file: No such file or directory
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1122:18)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/node_modules/ssvm/index.js:4:15)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
root@8a292042ecf0:/workspaces/ssvm-nodejs-starter# 
```

What I can do to resolve it.

**Comment by hydai** [comment]
Hi @anthhub, thanks for reporting this issue.
We've update the README to switch dockerfile from v1 to v2. To support new features of ssvm, we added more dependencies which are LLVM libraries. You can use `sudo apt install  llvm-dev liblld-10-dev` to fix this issue on your current environment.

**Comment by anthhub** [comment]
Thanks for your reply!

The crash happened when I run code by locally Docker and VS Codespaces, it lunched successfully by dockerfile v1 in Docker.

![image](https://user-images.githubusercontent.com/38548475/97943149-5a8bc300-1dbf-11eb-93a2-a207bfa4aceb.png)

![image](https://user-images.githubusercontent.com/38548475/97944013-96268d00-1dbf-11eb-947b-59e30efb46d6.png)

**Comment by hydai** [comment]
Hi @anthhub 
Oh, we only update the dockerfile only. Sorry about that. I've updated another dockerfile for VS codespace just now.
You can simply type `apt install llvm-dev liblld-10-dev` on your codespace to fix it. Or re-deploy a new codespace. This issue should be fixed now.

**Comment by anthhub** [comment]
> Hi @anthhub, thanks for reporting this issue.
> We've update the README to switch dockerfile from v1 to v2. To support new features of ssvm, we added more dependencies which are LLVM libraries. You can use `sudo apt install llvm-dev liblld-10-dev` to fix this issue on your current environment.

**Comment by anthhub** [comment]
> Hi @anthhub
> Oh, we only update the dockerfile only. Sorry about that. I've updated another dockerfile for VS codespace just now.
> You can simply type `apt install llvm-dev liblld-10-dev` on your codespace to fix it. Or re-deploy a new codespace. This issue should be fixed now.

It works! Excellent!

Thank you very much!
