### ISSUE TITLE
Giveaway google form doesn't seem to be working

### ISSUE THREAD

**Issue by dhruvv** [second-state/ssvm-nodejs-starter#4]
I finished the challenge and tried to submit it but my form doesn't seem to have worked and I haven't received any confirmation of my submission. Could you please check it out? I really want the Raspberry Pi as I need a computer.

**Comment by mufti199** [comment]
@dhruvv Did you manage to hear back from them?
I just applied recently, the form did work but I didn't get any confirmation or anything.

**Comment by tpmccallum** [comment]
Hi @dhruvv and @mufti199 
I will chase this up for you.

**Comment by dhruvv** [comment]
Yeah, I did get a response and my Raspberry Pi is being shipped to me.

**Comment by mufti199** [comment]
@dhruvv That's great! You should close the issue then.

@tpmccallum  Thank you very much. I've gotten a response as well.

**Comment by Bearbobs** [comment]
@tpmccallum  can you please help me as well? also did not receive any confirmation.

**Comment by alabulei1** [comment]
> @tpmccallum can you please help me as well? also did not receive any confirmation.

Great job! We really hope you could continue your project! You will receive a confirmation email soon.

**Comment by Bearbobs** [comment]
yeah definitely.
Thanks got the mail
